name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

# Allow only one concurrent deployment per PR
concurrency:
  group: "preview-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        if: github.event.action != 'closed'

      - name: Setup Node
        uses: actions/setup-node@v4
        if: github.event.action != 'closed'
        with:
          node-version: "22"
          cache: 'pnpm'

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: pnpm install --frozen-lockfile

      - name: Build with Next.js
        if: github.event.action != 'closed'
        run: pnpm next build
        env:
          NODE_ENV: production

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./out/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
